version: "3.9"
   
services:
    postgres:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=app_db
            - POSTGRES_USER=user_db
            - POSTGRES_PASSWORD=password_db
    django:
        build:
            context: .
            dockerfile: DockerfileDjango
        command: python manage.py runserver 0.0.0.0:8000
        tty: true
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        restart: always
