version: "3.9"
   
services:
    mysql:
        image: mysql:8.0
        env_file:
            - ./env_variables/mysql.env
        volumes:
            - ./mysql:/var/lib/mysql
        restart: unless-stopped
        networks:
            - cepa
    django:
        build:
            context: .
            dockerfile: dockerfiles/DockerfileDjango
        env_file:
            - ./env_variables/django.env
        entrypoint: ["./entrypoint.sh"]
        volumes:
            - ./django:/app
        ports:
            - 8000:8000
        depends_on:
            - mysql
        restart: unless-stopped
        networks:
            - cepa
        tty: true

networks:
    cepa:
        external:
            name: cepa